"""
Core exceptions for the backend application.

This module contains custom exceptions used throughout the application
for proper error handling and API responses.
"""

# Re-export custom exceptions for backward compatibility
from backend.core.custom_exceptions import (
    AccountLockedError,
    AuthenticationError,
    AuthorizationError,
    CANBusOffError,
    CANError,
    CANInterfaceError,
    CANMessageError,
    CoachIQException,
    ConfigurationError,
    ConfigurationLoadError,
    DatabaseConnectionError,
    DatabaseError,
    DatabaseMigrationError,
    DataIntegrityError,
    EmailServiceError,
    EmergencyStopError,
    EntityAlreadyExistsError,
    EntityControlError,
    EntityError,
    EntityNotFoundError,
    ExternalServiceError,
    InputValidationError,
    InsufficientPermissionsError,
    InvalidCommandError,
    InvalidConfigurationError,
    InvalidCredentialsError,
    InvalidDGNError,
    InvalidSafetyPINError,
    InvalidTokenError,
    MFARequiredError,
    RangeValidationError,
    RateLimitExceededError,
    RoleRequiredError,
    RVCError,
    SafetyException,
    SafetyPINRequiredError,
    SafetyViolationError,
    ServiceDependencyError,
    ServiceHealthCheckError,
    ServiceInitializationError,
    ServiceNotAvailableError,
    TokenExpiredError,
    UnknownPGNError,
    ValidationError,
    VectorSearchError,
    WebSocketAuthenticationError,
    WebSocketError,
    WebSocketRateLimitError,
)

# All exceptions are now imported from custom_exceptions module
# This module serves as a backward compatibility layer

__all__ = [
    "AccountLockedError",
    "AuthenticationError",
    "AuthorizationError",
    "CANBusOffError",
    "CANError",
    "CANInterfaceError",
    "CANMessageError",
    "CoachIQException",
    "ConfigurationError",
    "ConfigurationLoadError",
    "DataIntegrityError",
    "DatabaseConnectionError",
    "DatabaseError",
    "DatabaseMigrationError",
    "EmailServiceError",
    "EmergencyStopError",
    "EntityAlreadyExistsError",
    "EntityControlError",
    "EntityError",
    "EntityNotFoundError",
    "ExternalServiceError",
    "InputValidationError",
    "InsufficientPermissionsError",
    "InvalidCommandError",
    "InvalidConfigurationError",
    "InvalidCredentialsError",
    "InvalidDGNError",
    "InvalidSafetyPINError",
    "InvalidTokenError",
    "MFARequiredError",
    "RVCError",
    "RangeValidationError",
    "RateLimitExceededError",
    "RoleRequiredError",
    "SafetyException",
    "SafetyPINRequiredError",
    "SafetyViolationError",
    "ServiceDependencyError",
    "ServiceHealthCheckError",
    "ServiceInitializationError",
    "ServiceNotAvailableError",
    "TokenExpiredError",
    "UnknownPGNError",
    "ValidationError",
    "VectorSearchError",
    "WebSocketAuthenticationError",
    "WebSocketError",
    "WebSocketRateLimitError",
]
