site_name: CoachIQ - Personal RV Control
site_description: Raspberry Pi based RV control system
site_url: https://carpenike.github.io/coachiq
repo_url: https://github.com/carpenike/coachiq

use_directory_urls: true
docs_dir: docs
site_dir: site

nav:
  - Home: README.md
  - Setup: setup.md
  - Usage: usage.md
  - Troubleshooting: troubleshooting.md
  - Safety: safety.md
  - API: api/reference.md

theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy
  palette:
    primary: indigo
    accent: amber

plugins:
  - search
  - swagger-ui-tag

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
