[build-system]
requires    = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name        = "rvc2api"
version     = "0.1.0"
description = "CAN‑bus web service exposing RV‑C network data via HTTP & WebSocket"
readme      = "README.md"
license     = "MIT"
authors     = ["Ryan Holt <ryan@ryanholt.net>"]

# PyPI metadata
keywords    = ["can", "rv-c", "websocket", "fastapi"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX :: Linux",
]

# src layout and extra files
packages = [
  { include = "rvc_decoder", from = "src" },
]
include = [
  "src/rvc_decoder/config/rvc.json",
  "src/rvc_decoder/config/device_mapping.yml",
]

[tool.poetry.dependencies]
python = ">=3.12"
fastapi    = "^0.95"
uvicorn    = { extras = ["standard"], version = "^0.22" }
python-can = "^4.0"
pydantic   = "^1.10"
pyyaml     = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2"
mypy   = "^1.5"
flake8 = "^6.0"

[tool.poetry.urls]
Homepage   = "https://github.com/carpenike/rvc2api"
Repository = "https://github.com/carpenike/rvc2api"
