name: Deploy MkDocs

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-deps-${{ hashFiles('requirements.txt') }}
          path: ~/.cache/pip
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate OpenAPI schema
        run: |
          poetry run python scripts/export_openapi.py
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
