name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "web_ui/**"
  pull_request:
    branches: [main]
    paths:
      - "web_ui/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix (with flakes enabled)
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Nix cache
        uses: cachix/cachix-action@v16
        with:
          name: rvc2api
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.ref != 'refs/heads/main' }}

      - name: Run frontend checks in Nix shell
        run: |
          nix develop --command bash -c '
            cd web_ui
            npm ci
            npm run lint
            npm run typecheck
            npm run build
          '

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: web_ui/dist/
          retention-days: 7
