name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "web_ui/**"
  pull_request:
    branches: [main]
    paths:
      - "web_ui/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix (with flakes enabled)
        uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Nix cache
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: rvc2api
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.ref != 'refs/heads/main' }}

      - name: Run frontend checks in Nix shell
        run: |
          nix develop --command bash -c '
            cd web_ui
            npm ci
            npm run lint
            npm run typecheck
            npm run build
          '

      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: frontend-build
          path: web_ui/dist/
          retention-days: 7
