# GitHub Actions workflow for Nix-based continuous integration
name: "Nix-based CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: "Full CI (pre-commit, tests, lints, lock-check)"
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: "Install Nix (with flakes enabled)"
        uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: "Setup Nix cache"
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: rvc2api
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.ref != 'refs/heads/main' }}

      - name: "Perform Nix flake ci"
        run: nix run .#ci

  flake-build:
    name: Nix flake checks & build
    needs: ci
    runs-on: ubuntu-latest
    environment: default

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: "Install Nix (with flakes enabled)"
        uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: "Setup Nix cache"
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: rvc2api
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.ref != 'refs/heads/main' }}

      - name: Run all flake checks (includes lock‑check from checks, and will build rvc2api)
        run: nix flake check
