# GitHub Actions workflow for Nix-based continuous integration
name: "Nix-based CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: "Full CI (pre-commit, tests, lints, lock-check)"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Install Nix (with flakes enabled)"
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: "Setup Nix cache"
        uses: cachix/cachix-action@v16
        with:
          name: rvc2api
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.ref != 'refs/heads/main' }}

      - name: "Perform Nix flake ci"
        run: nix run .#ci

  flake-build:
    name: Nix flake checks & build
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Install Nix (with flakes enabled)"
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: "Setup Nix cache"
        uses: cachix/cachix-action@v16
        with:
          name: rvc2api
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: ${{ github.ref != 'refs/heads/main' }}

      - name: Run all flake checks (includes lock‑check from checks, and will build rvc2api)
        run: nix flake check
