name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-and-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump & draft release
        uses: google-github-actions/release-please-action@v4
        with:
          # this is automatically provided by GitHub; no need to create your own PAT
          token: ${{ secrets.GITHUB_TOKEN }}

          # point at your new manifest
          manifest-file: .release-please-manifest.json
