name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-and-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump & draft release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
